{"success": true, "error": null, "issues": [{"title": "Exception state", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ", "function": "_function_0x546455b5", "type": "Informational", "address": 446, "debug": "The exception is triggered under the following conditions:\n\ncalldata_Exceptions_0: 0x546455b500000000000000000000000000000000000000000000000000000000\ncalldatasize_Exceptions: 0x4\ncalldata_Exceptions_4: 0x17\ncallvalue: 0x0\n", "filename": "<TEST_FILES>/exceptions.sol", "lineno": 16, "code": "assert(input != 23)"}, {"title": "Exception state", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ", "function": "_function_0x92dd38ea", "type": "Informational", "address": 484, "debug": "The exception is triggered under the following conditions:\n\ncalldata_Exceptions_4: 0x8\ncalldata_Exceptions_0: 0x92dd38ea00000000000000000000000000000000000000000000000000000000\ncalldatasize_Exceptions: 0x4\ncallvalue: 0x0\n", "filename": "<TEST_FILES>/exceptions.sol", "lineno": 34, "code": "myarray[index]"}, {"title": "Exception state", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ", "function": "_function_0xa08299f1", "type": "Informational", "address": 506, "debug": "The exception is triggered under the following conditions:\n\ncalldata_Exceptions_0: 0xa08299f100000000000000000000000000000000000000000000000000000000\ncalldatasize_Exceptions: 0x4\ncalldata_Exceptions_4: 0x0\ncallvalue: 0x0\n", "filename": "<TEST_FILES>/exceptions.sol", "lineno": 24, "code": "1/input"}, {"title": "Exception state", "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ", "function": "_function_0xb34c3610", "type": "Informational", "address": 531, "debug": "The exception is triggered under the following conditions:\n\ncalldata_Exceptions_0: 0xb34c361000000000000000000000000000000000000000000000000000000000\ncalldatasize_Exceptions: 0x4\ncallvalue: 0x0\n", "filename": "<TEST_FILES>/exceptions.sol", "lineno": 7, "code": "assert(i == 0)"}]}