{
    "success": true,
    "error": null,
    "issues": [
        {
            "title": "Dependence on predictable environment variable",
            "description": "In the function '_function_0xe9874106' the following predictable state variables are used to determine Ether recipient:\n- block.coinbase\n",
            "function": "_function_0xe9874106",
            "type": "Warning",
            "address": 1285,
            "debug": "<DEBUG-DATA>",
            "filename": "<TEST_FILES>/inputs/weak_random.sol",
            "lineno": 47,
            "code": "winningAddress.transfer(prize)"
        },
        {
            "title": "Ether send",
            "description": "In the function '_function_0xe9874106' a non-zero amount of Ether is sent to an address taken from storage slot 0.\nThere is a check on storage index 0. This storage slot can be written to by calling the function 'fallback'.\n\nThere is a check on storage index 1. This storage slot can be written to by calling the function 'fallback'.\nThere is a check on storage index 1. This storage slot can be written to by calling the function 'fallback'.",
            "function": "_function_0xe9874106",
            "type": "Warning",
            "address": 1285,
            "debug": "<DEBUG-DATA>",
            "filename": "<TEST_FILES>/inputs/weak_random.sol",
            "lineno": 47,
            "code": "winningAddress.transfer(prize)"
        },
        {
            "title": "Exception state",
            "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ",
            "function": "fallback",
            "type": "Informational",
            "address": 356,
            "debug": "<DEBUG-DATA>",
            "filename": "<TEST_FILES>/inputs/weak_random.sol",
            "lineno": 11,
            "code": "prize / totalTickets"
        },
        {
            "title": "Exception state",
            "description": "A reachable exception (opcode 0xfe) has been detected. This can be caused by type errors, division by zero, out-of-bounds array access, or assert violations. This is acceptable in most situations. Note however that assert() should only be used to check invariants. Use require() for regular input checking. ",
            "function": "_function_0xe9874106",
            "type": "Informational",
            "address": 146,
            "debug": "<DEBUG-DATA>",
            "filename": "<TEST_FILES>/inputs/weak_random.sol",
            "lineno": 11,
            "code": "prize / totalTickets"
        }
    ]
}